### ISSUE TITLE
无法自动重命名

### ISSUE THREAD

**Issue by moonan3019** [Nriver/qb-rss-manager#1]
你好 有个问题请教一下 我按照教程使用了懒人包 订阅和下载都很成功，但是下载之后并没有重命名 我的下载文件路径为E:\Media\Anime\Kaguya-sama Love Is War\Season 3  这是我哪里设置的不对吗

**Comment by Nriver** [comment]
文件名是什么

**Comment by moonan3019** [comment]
下载下来的文件名为[Lilith-Raws] Kaguya-sama wa Kokurasetai S03 - 07 [Baha][WEB-DL][1080p][AVC AAC][CHT][MP4].mp4

**Comment by Nriver** [comment]
我试了直接用重命名工具是可以重命名的，说明重命名工具是支持这个文件名的。
没有重命名可能是ab参数没设置正确，请参考 https://github.com/Nriver/Episode-ReName 的说明检查一下设置。

**Comment by moonan3019** [comment]
好的 我明天试一下 麻烦您了

**Comment by Nriver** [comment]
我这边测试没有问题，缺少后续反馈，先关闭了
