### ISSUE TITLE
集数修正出错？如何进行版本更新？

### ISSUE THREAD

**Issue by nostphi** [Nriver/qb-rss-manager#12]
<img width="548" alt="image" src="https://github.com/Nriver/qb-rss-manager/assets/119793232/d5dbff92-dead-4828-bc63-356050f45a09">
<img width="800" alt="image" src="https://github.com/Nriver/qb-rss-manager/assets/119793232/3015e58b-38d5-4424-9785-b10faa462615">
<img width="376" alt="image" src="https://github.com/Nriver/qb-rss-manager/assets/119793232/0e8b8680-8fb9-41f9-9474-7ff5bcfe26bd">
前两个是手动改的

**Comment by nostphi** [comment]
另外想问下怎么更新，直接替换就行了吗，原有manager和qbit的数据会保留吗

**Comment by Nriver** [comment]
修正没有问题

下面的例子，15秒后自动改名，29 - 25 = 4

![1](https://github.com/Nriver/qb-rss-manager/assets/6752679/12da0981-6d5e-4a3a-ac35-bd8e4b592508)

更新要保留数据就只复制exe文件

**Comment by nostphi** [comment]
好奇怪，我更新完又试了，我的还是不会减25，应该不是我把15秒改成10秒的原因吧？
另外顺便一提，你给的例子，第二季好像变成了S01了

**Comment by Nriver** [comment]
测试是直接下载release，只改了关键字和修正数字，没改目录名称，季数是根据目录读取的。

**Comment by nostphi** [comment]
我刚刚也想直接下载release测试，原来的文件不动，我在别的文件夹里解压。但是操作下来，rss里更新不了以前的feed。
这个正常吗？

**Comment by Nriver** [comment]
feed可以改host或者在qb里设置代理，勾选只对种子生效。

**Comment by nostphi** [comment]
直接下载release测试确实没有问题，现在在考虑把数据移过来，直接替换config.json文件可以吗？

**Comment by Nriver** [comment]
可以。不过以防万一先备份。
